# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-11 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyToken',
            fields=[
            ],
            options={
                'verbose_name': 'Token',
                'proxy': True,
                'indexes': [],
            },
            bases=('authtoken.token',),
        ),
    ]
