# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 16:52
from __future__ import unicode_literals

import apps.boxes.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoxProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=apps.boxes.models.user_box_upload_path)),
                ('checksum_type', models.CharField(choices=[('md5', 'md5'), ('sha1', 'sha1'), ('sha256', 'sha256')], default='sha256', max_length=10)),
                ('checksum', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BoxVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Invalid version number. It must be of the format X.Y.Z where X, Y, and Z are all positive integers.', regex='^(\\d+)\\.(\\d+)(\\.(\\d+))?$')])),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='boxes.Box')),
            ],
        ),
        migrations.AddField(
            model_name='boxprovider',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='boxes.BoxVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='boxversion',
            unique_together=set([('box', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='boxprovider',
            unique_together=set([('version', 'provider')]),
        ),
        migrations.AlterUniqueTogether(
            name='box',
            unique_together=set([('owner', 'name')]),
        ),
    ]
