# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 18:07
from __future__ import unicode_literals

import apps.boxes.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxprovider',
            name='pulls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boxprovider',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location='/home/vagrant/vagrant_registry/protected_media'), upload_to=apps.boxes.models.user_box_upload_path),
        ),
    ]
