# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_boxchunkedupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxchunkedupload',
            name='upload_id',
        ),
        migrations.AlterField(
            model_name='boxchunkedupload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
