# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_auto_20160609_1741'),
    ]

    operations = [
        migrations.RenameModel('BoxChunkedUpload', 'BoxUpload')
    ]
