# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 18:26
from __future__ import unicode_literals

from django.utils import timezone

import apps.boxes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_auto_20160609_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxupload',
            old_name='name',
            new_name='box_name',
        ),
        migrations.AddField(
            model_name='boxupload',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boxupload',
            name='checksum_type',
            field=models.CharField(choices=[('md5', 'md5'), ('sha1', 'sha1'), ('sha256', 'sha256')], max_length=10),
        ),
        migrations.AlterField(
            model_name='boxupload',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=apps.boxes.models.chunked_upload_path),
        ),
    ]
