# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_auto_20160609_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxupload',
            name='user',
        ),
        migrations.RemoveField(
            model_name='boxupload',
            name='box_name',
        ),
        migrations.AddField(
            model_name='boxupload',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='boxes.Box'),
            preserve_default=False,
        ),
    ]
