# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_auto_20160609_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxupload',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
