# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 17:46
from __future__ import unicode_literals

import apps.boxes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0007_boxupload_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxprovider',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boxupload',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.boxes.models.chunked_upload_path),
        ),
    ]
