# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0008_auto_20160629_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 10, 13, 38, 14, 588658, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxprovider',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 10, 13, 38, 52, 722827, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxversion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 10, 13, 39, 0, 275310, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
