# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0009_auto_20160710_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='private',
        ),
        migrations.AddField(
            model_name='box',
            name='visibility',
            field=models.CharField(choices=[('PT', 'Private'), ('AU', 'All users'), ('PC', 'Public')], default='PT', max_length=2),
        ),
    ]
