# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0011_auto_20160710_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'permissions': (('pull_box', 'Pull box'), ('push_box', 'Push box'))},
        ),
    ]
