# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0013_auto_20160711_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'permissions': (('pull_box', 'Can pull box'), ('push_box', 'Can push box'))},
        ),
    ]
