# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boxes', '0014_auto_20160712_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(blank=True, choices=[('R', 'View/pull box'), ('RW', 'View/pull/push box')], default='RW', max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='box',
            options={},
        ),
        migrations.AddField(
            model_name='boxmember',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.Box'),
        ),
        migrations.AddField(
            model_name='boxmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='box',
            name='shared_with',
            field=models.ManyToManyField(through='boxes.BoxMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
