# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0015_auto_20160717_1039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boxgroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='boxgroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='boxgroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='boxgroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='boxuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='boxuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='boxuserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='boxuserobjectpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='BoxGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='BoxUserObjectPermission',
        ),
    ]
