# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0016_auto_20160717_1047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boxmember',
            unique_together=set([('user', 'box')]),
        ),
    ]
