# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 18:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0017_auto_20160717_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[\\w]+$', 'Enter a valid name. This value may contain only letters and numbers.')]),
        ),
    ]
