# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('boxes_permissions', models.CharField(blank=True, choices=[('', 'No permissions'), ('R', 'View/pull boxes'), ('RW', 'View/pull/push boxes')], default='RW', max_length=2)),
            ],
        ),
    ]
