# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-11 19:45
from __future__ import unicode_literals

import apps.boxes.models
from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated')),
                ('visibility', models.CharField(choices=[('PT', 'Private'), ('PC', 'Public')], default='PT', max_length=2)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid name. Name may contain letters, digits and @/./+/- only.')])),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'boxes',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='BoxMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(blank=True, choices=[('R', 'View/pull box'), ('RW', 'View/pull/push box')], default='RW', max_length=2)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.Box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='BoxProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location='C:\\Users\\artem\\Projects\\vagrant_registry\\vagrant_registry\\api\\protected_media'), upload_to=apps.boxes.models.user_box_upload_path)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum_type', models.CharField(choices=[('md5', 'md5'), ('sha1', 'sha1'), ('sha256', 'sha256')], default='sha256', max_length=10)),
                ('checksum', models.CharField(max_length=128)),
                ('pulls', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('EM', 'Empty'), ('FI', 'Filled in')], default='EM', max_length=2)),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='BoxUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location='C:\\Users\\artem\\Projects\\vagrant_registry\\vagrant_registry\\api\\protected_media'), upload_to=apps.boxes.models.chunked_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('offset', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('S', 'Started'), ('I', 'In progress'), ('C', 'Completed')], default='S', max_length=1)),
                ('checksum_type', models.CharField(choices=[('md5', 'md5'), ('sha1', 'sha1'), ('sha256', 'sha256')], max_length=10)),
                ('checksum', models.CharField(max_length=128)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='boxes.BoxProvider')),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='BoxVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated')),
                ('version', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Invalid version number. It must be of the format X.Y.Z where X, Y, and Z are all positive integers.', regex='^(\\d+)\\.(\\d+)(\\.(\\d+))?$')])),
                ('changes', models.TextField(blank=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='boxes.Box')),
            ],
            options={
                'verbose_name_plural': 'box versions',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.AddField(
            model_name='boxprovider',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='boxes.BoxVersion'),
        ),
        migrations.AddField(
            model_name='box',
            name='shared_with',
            field=models.ManyToManyField(through='boxes.BoxMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='boxversion',
            unique_together=set([('box', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='boxprovider',
            unique_together=set([('version', 'provider')]),
        ),
        migrations.AlterUniqueTogether(
            name='boxmember',
            unique_together=set([('user', 'box')]),
        ),
        migrations.AlterUniqueTogether(
            name='box',
            unique_together=set([('owner', 'name')]),
        ),
    ]
