# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='boxprovider',
            name='checksum',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='boxprovider',
            name='checksum_type',
            field=models.CharField(choices=[('md5', 'md5'), ('sha1', 'sha1'), ('sha256', 'sha256')], default='sha256', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='boxprovider',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='boxprovider',
            name='file_size',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='boxprovider',
            name='pulls',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='boxprovider',
            name='status',
            field=models.CharField(choices=[('EM', 'Empty'), ('FI', 'Filled in')], default='EM', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='boxversion',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Last updated'),
        ),
        migrations.AlterUniqueTogether(
            name='boxupload',
            unique_together=set([('provider', 'checksum')]),
        ),
    ]
