# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['-date_modified'], 'verbose_name_plural': 'boxes'},
        ),
        migrations.AlterModelOptions(
            name='boxmember',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='boxprovider',
            options={'ordering': ['-date_modified']},
        ),
        migrations.AlterModelOptions(
            name='boxupload',
            options={'ordering': ['-date_modified']},
        ),
        migrations.AlterModelOptions(
            name='boxversion',
            options={'ordering': ['-date_modified'], 'verbose_name_plural': 'box versions'},
        ),
        migrations.AddField(
            model_name='box',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='boxprovider',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='boxversion',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated'),
        ),
    ]
